### ISSUE TITLE
用自己的文本总会出现 index out of range

### ISSUE THREAD

**Issue by Crescentz** [yanwii/seq2seq#19]
Traceback (most recent call last):
  File "seq2seq.py", line 439, in <module>
    seq.train()
  File "seq2seq.py", line 210, in train
    loss, logits = self.step(inputs, targets, self.max_length)
  File "seq2seq.py", line 236, in step
    encoder_outputs, encoder_hidden = self.encoder(input_variable, encoder_hidden)
  File "/home/zy/anaconda3/envs/pytchar/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "seq2seq.py", line 35, in forward
    embedded = self.embedding(word_inputs).view(seq_len, 1, -1)
  File "/home/zy/anaconda3/envs/pytchar/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zy/anaconda3/envs/pytchar/lib/python3.7/site-packages/torch/nn/modules/sparse.py", line 110, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/home/zy/anaconda3/envs/pytchar/lib/python3.7/site-packages/torch/nn/functional.py", line 1110, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: index out of range at /opt/conda/conda-bld/pytorch_1535493744281/work/aten/src/TH/generic/THTensorMath.cpp:352

**Comment by Crescentz** [comment]
找到原因了  方法中的input和out size 您是自己设置的 不是根据数据的字典大小动态设置的。
