### ISSUE TITLE
RuntimeError: cuda runtime error (59) : 

### ISSUE THREAD

**Issue by liutianling** [yanwii/seq2seq#21]
在问答集中增加问题后，就报了这个错误。
我就改了这几个参数
        self.input_size = 1840
        self.output_size = 1840
        self.hidden_size = 64
        self.max_length = 50
/pytorch/torch/lib/THCUNN/ClassNLLCriterion.cu:57: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [0,0,0] Assertion `t >= 0 && t < n_classes` failed.
THCudaCheck FAIL file=/pytorch/torch/lib/THC/generic/THCTensorCopy.c line=18 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "seq2seq.py", line 443, in <module>
    seq.retrain()
  File "seq2seq.py", line 434, in retrain
    self.train()
  File "seq2seq.py", line 213, in train
    loss, logits = self.step(inputs, targets, self.max_length)
  File "seq2seq.py", line 253, in step
    decoder_output, decoder_context, decoder_hidden, decoder_attention = self.decoder(decoder_input, decoder_context, decoder_hidden, encoder_outputs)
  File "/home/liuyong/venv/seq2seq-master/lib/python3.5/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "seq2seq.py", line 105, in forward
    attn_weights = self.attn(rnn_output.squeeze(0), encoder_outputs)
  File "/home/liuyong/venv/seq2seq-master/lib/python3.5/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "seq2seq.py", line 63, in forward
    if USE_CUDA: attn_energies = attn_energies.cuda()
  File "/home/liuyong/venv/seq2seq-master/lib/python3.5/site-packages/torch/autograd/variable.py", line 279, in cuda
    return CudaTransfer.apply(self, device_id, async)
  File "/home/liuyong/venv/seq2seq-master/lib/python3.5/site-packages/torch/autograd/_functions/tensor.py", line 151, in forward
    return i.cuda(async=async)
  File "/home/liuyong/venv/seq2seq-master/lib/python3.5/site-packages/torch/_utils.py", line 66, in _cuda
    return new_type(self.size()).copy_(self, async)

**Comment by yanwii** [comment]
试着把output_size调大一点

**Comment by liutianling** [comment]
@yanwii 
谢谢，确实要调大点。
关于提高问答准确度的问题：
１、分词与否，预测时回答的合理性有没有影响
２、哪些手段可以(包括数据的预处理)可以使对话更加合理？
谢谢。。。

**Comment by yanwii** [comment]
1.在中文nlp任务中，大部分任务用分词的特征结果都会比不分词的效果好
2.这个模型依赖大量数据。如果要做机器人，光有这个模型是不够的，因为它属于推断模型，结果太不可控了。

**Comment by liutianling** [comment]
@yanwii 非常感谢你的详细解答，谢谢。
