### ISSUE TITLE
替换了自己的数据之后会报错

### ISSUE THREAD

**Issue by iamxufan** [yanwii/seq2seq#25]
```
/Users/xufan/anaconda3/python.app/Contents/lib/python3.6/site-packages/torch/nn/modules/rnn.py:54: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.01 and num_layers=1
  "num_layers={}".format(dropout, num_layers))
/Users/xufan/Desktop/itemq/seq2seq.py:70: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return F.softmax(attn_energies).unsqueeze(0).unsqueeze(0)
/Users/xufan/Desktop/itemq/seq2seq.py:112: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  output = F.log_softmax(self.out(torch.cat((rnn_output, context), 1)))
/Users/xufan/Desktop/itemq/seq2seq.py:268: UserWarning: torch.nn.utils.clip_grad_norm is now deprecated in favor of torch.nn.utils.clip_grad_norm_.
  torch.nn.utils.clip_grad_norm(self.encoder.parameters(), clip)
/Users/xufan/Desktop/itemq/seq2seq.py:269: UserWarning: torch.nn.utils.clip_grad_norm is now deprecated in favor of torch.nn.utils.clip_grad_norm_.
  torch.nn.utils.clip_grad_norm(self.decoder.parameters(), clip)
--------------------------------------------------
epoch: 0
    loss: 0.0017108917236328125
    target:[3, 1]
    output:[3, 1]
    per-time: 1.0286190509796143
--------------------------------------------------
epoch: 2
    loss: 2.617159684499105
    target:[4, 5, 6, 7, 8, 1]
    output:[3, 1, 1, 1, 1, 1]
    per-time: 0.9947419166564941
--------------------------------------------------
epoch: 4
    loss: 4.294578552246094
    target:[12, 13, 14, 15, 16, 12, 17, 1]
    output:[3, 1, 5, 15, 1, 1, 1, 1]
    per-time: 1.1878671646118164
Traceback (most recent call last):
  File "/Users/xufan/Desktop/itemq/train.py", line 4, in <module>
    seq.train()
  File "/Users/xufan/Desktop/itemq/seq2seq.py", line 212, in train
    loss, logits = self.step(inputs, targets, self.max_length)
  File "/Users/xufan/Desktop/itemq/seq2seq.py", line 253, in step
    loss += self.criterion(decoder_output, target_variable[di])
  File "/Users/xufan/anaconda3/python.app/Contents/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/Users/xufan/anaconda3/python.app/Contents/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 209, in forward
    return F.nll_loss(input, target, weight=self.weight, ignore_index=self.ignore_index, reduction=self.reduction)
  File "/Users/xufan/anaconda3/python.app/Contents/lib/python3.6/site-packages/torch/nn/functional.py", line 1871, in nll_loss
    ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: Assertion `cur_target >= 0 && cur_target < n_classes' failed.  at ../aten/src/THNN/generic/ClassNLLCriterion.c:92
```

**Comment by iamxufan** [comment]
修改seq2seq.py的
```
self.input_size = 1000
# 由1300修改到2000可以运行
self.output_size = 2000
self.hidden_size = 1400
```
请问具体的参数含义是什么呢？ @yanwii

**Comment by yanwii** [comment]
input_size 表示encoder词典大小
output_size 表示decoder词典大小
hidden_size 则为lstm的参数
