### ISSUE TITLE
Expected argument self to have 1

### ISSUE THREAD

**Issue by jaysharp** [yanwii/seq2seq#3]
执行：
python3 preprocessing.py
python3 seq2seq.py train
之后，出现：
请问是不是python或pytorch的版本不对？

Traceback (most recent call last):
  File "seq2seq.py", line 438, in <module>
    seq.train()
  File "seq2seq.py", line 213, in train
    loss, logits = self.step(inputs, targets, self.max_length)
  File "seq2seq.py", line 253, in step
    decoder_output, decoder_context, decoder_hidden, decoder_attention = self.decoder(decoder_input, decoder_context, decoder_hidden, encoder_outputs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "seq2seq.py", line 109, in forward
    attn_weights = self.attn(rnn_output.squeeze(0), encoder_outputs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "seq2seq.py", line 65, in forward
    attn_energies[i] = self.score(hidden, encoder_outputs[i])
  File "seq2seq.py", line 76, in score
    energy = hidden.dot(energy)
  File "/usr/local/lib/python3.5/dist-packages/torch/autograd/variable.py", line 631, in dot
    return Dot.apply(self, other)
  File "/usr/local/lib/python3.5/dist-packages/torch/autograd/_functions/blas.py", line 211, in forward
    return vector1.new((vector1.dot(vector2),))
RuntimeError: Expected argument self to have 1 dimension(s), but has 2 at /pytorch/torch/csrc/generic/TensorMethods.cpp:23020

**Comment by yanwii** [comment]
的确是版本问题 先安装以下版本  后续我会更新
python2.7
pip install http://download.pytorch.org/whl/cu80/torch-0.1.11.post5-cp27-none-linux_x86_64.whl 
pip install torchvision

python3.5
pip install http://download.pytorch.org/whl/cu80/torch-0.1.11.post5-cp35-cp35m-linux_x86_64.whl 
pip install torchvision

python3.6
pip install http://download.pytorch.org/whl/cu80/torch-0.1.11.post5-cp36-cp36m-linux_x86_64.whl 
pip install torchvision

**Comment by jaysharp** [comment]
多谢

**Comment by yanwii** [comment]
非常抱歉，已经更新。
建议将Pytorch升级至2.0，以获得更好的体验。
